hello_django/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import patterns, url
from polls import views

urlpatterns = patterns('',
   url(r'^$', views.index, name='index'),
   url(r'^(?P<question_id>\d+)/$', views.show, name='show'),
   url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
   url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),
)

polls/models.py
from __future__ import unicode_literals

from django.db import models


class Question(models.Model):
    text = models.CharField(max_length=200)
    created_at = models.DateTimeField('date published')

    def __unicode__(self):
        return self.text


class Alternative(models.Model):
    question = models.ForeignKey(Question)
    text = models.CharField(max_length=200)
    vote_count = models.IntegerField(default=0)

    def __unicode__(self):
        return self.text

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from polls.models import Alternative, Question


def index(request):
    questions = Question.objects.all().order_by('-created_at')[:5]
    return render(request, 'polls/index.html', {'questions': questions})


def show(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/show.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_alternative = question.alternative_set.get(pk=request.POST['alternative'])
    except (KeyError, Alternative.DoesNotExist):
        return render(request, 'polls/show.html', {
            'question': question,
            'error_message': 'Select one!'
        })
    else:
        selected_alternative.vote_count += 1
        selected_alternative.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

polls/templates/polls/index.html
{% if questions %}
  <ul>
    {% for question in questions %}
      <li>
        <a href="/polls/{{ question.id }}/">
          {{ question.text }}
        </a>
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>
    Polls not found~
  </p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.text }}</h1>

<ul>
  {% for alternative in question.alternative_set.all %}
    <li>
      {{ alternative.text }} - {{ alternative.vote_count }} vote{{ alternative.vote_count|pluralize }}
    </li>
  {% endfor %}
</ul>

<a href="{% url 'polls:show' question.id %}">
  Vote Again?
</a>

polls/templates/polls/show.html
<h1>{{ question.text }}</h1>

{% if error_message %}
  <p>{{ error_message }}</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  {% for alternative in question.alternative_set.all %}
    <div>
      <input type="radio" name="alternative" id="alternative{{ forloop.counter }}" value="{{ alternative.id }}"/>
      <label for="alternative{{ forloop.counter }}">
        {{ alternative.text }}
      </label>
    </div>
  {% endfor %}

  <button type="submit">Vote</button>
</form>